# Generated by Django 5.2.8 on 2025-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_app", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="status",
            field=models.CharField(default="Borrowed", max_length=200),
        ),
    ]
