# Generated by Django 5.2.8 on 2025-12-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="senderobj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
