# Generated by Django 5.2.8 on 2025-11-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="role",
            new_name="rolename",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_role",
                to="article_app.role",
            ),
        ),
    ]
