# Generated by Django 5.2.8 on 2025-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="eventName",
            field=models.CharField(default="Rock Concert", max_length=200),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(default="booked", max_length=200),
        ),
    ]
